import "./globals.css";
import localFont from "next/font/local";

const spaceGroteskFont = localFont({
  src: "../public/fonts/space-grotesk_variable-font_wght.ttf",
  variable: "--font-space-grotesk",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${spaceGroteskFont.variable} font-sans`}>
      <body>
        {children}
      </body>
    </html>
  );
}
